# Generated by Django 5.1.1 on 2025-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuenta', models.CharField(max_length=255)),
                ('tipo_cuenta', models.CharField(choices=[('AC', 'Activo Circulante'), ('ANC', 'Activo No Circulante'), ('P', 'Pasivo'), ('PT', 'Patrimonio'), ('C', 'Costoso gastos'), ('I', 'Ingresos'), ('CC', 'Cuentas de Cierre'), ('CEA', 'Cuentas Analíticas de Explotación')], max_length=50)),
                ('tipo_monto', models.CharField(choices=[('D', 'Debe'), ('H', 'Haber')], max_length=5)),
                ('monto', models.FloatField()),
                ('glose', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saldo_Inicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=100)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
