valores_cuentas = [
    "10",
"11",
"12",
"13",
"14",
"16",
"17",
"18",
"20",
"21",
"22",
"23",
"24",
"25",
"26",
"27",
"28",
"29",
"30",
"31",
"32",
"33",
"34",
"35",
"36",
"37",
"38",
"39",
"40",
"41",
"42",
"43",
"44",
"45",
"46",
"47",
"48",
"49",
"50",
"51",
"52",
"56",
"57",
"58",
"60",
"61",
"62",
"63",
"64",
"65",
"66",
"67",
"68",
"69",
"81",
"82",
"83",
"84",
"85",
"87",
"88",
"89",
"91",
"92",
"93",
"94",
"95",
"96",
"70",
"71",
"72",
"73",
"74",
"75",
"76",
"77",
"78",
"79",
]

tipo_cuenta_valor = [
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "AC",
    "ANC",
    "ANC",
    "ANC",
    "ANC",
    "ANC",
    "ANC",
    "ANC",
    "ANC",
    "ANC",
    "ANC",
    "P",
    "P",
    "P",
    "P",
    "P",
    "P",
    "P",
    "P",
    "P",
    "P",
    "PT",
    "PT",
    "PT",
    "PT",
    "PT",
    "PT",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "CC",
    "CC",
    "CC",
    "CC",
    "CC",
    "CC",
    "CC",
    "CC",
    "CEA",
    "CEA",
    "CEA",
    "CEA",
    "CEA",
    "CEA",
    "I",
    "I",
    "I",
    "I",
    "I",
    "I",
    "I",
    "I",
    "I",
    "I",
]

cuentas_dict = [
    ('10', '10 EFECTIVO Y EQUIVALENTES DE EFECTIVO'),
    ('11', '11 INVERSIONES FINANCIERAS'),
    ('12', '12 CUENTAS POR COBRAR COMERCIALES TERCEROS'),
    ('13', '13 CUENTAS POR COBRAR COMERCIALES RELACIONADAS'),
    ('14', '14 CUENTAS POR COBRAR AL PERSONAL, A LOS ACCIONISTAS'),
    ('16', '16 CUENTAS POR COBRAR DIVERSAS TERCEROS'),
    ('17', '17 CUENTAS POR COBRAR DIVERSAS RELACIONADAS'),
    ('18', '18 SERVICIOS Y OTROS CONTRATADOS POR ANTICIPADO'),
    ('20', '20 MERCADERÍAS'),
    ('21', '21 PRODUCTOS TERMINADOS'),
    ('22', '22 SUBPRODUCTOS, DESECHOS Y DESPERDICIOS'),
    ('23', '23 PRODUCTOS EN PROCESO'),
    ('24', '24 MATERIAS PRIMAS'),
    ('25', '25 MATERIALES AUXILIARES, SUMINISTROS Y REPUESTO'),
    ('26', '26 ENVASES Y EMBALAJES'),
    ('27', '27 ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA'),
    ('28', '28 EXISTENCIAS POR RECIBIR'),
    ('29', '29 DESVALORIZACIÓN DE EXISTENCIAS'),
    ('30', '30 INVERSIONES MOBILIARIAS'),
    ('31', '31 INVERSIONES INMOBILIARIAS'),
    ('32', '32 ACTIVOS ADQUIRIDOS EN ARRENDAMIENTO FINANCIERO'),
    ('33', '33 INMUEBLES, MAQUINARIA Y EQUIPO'),
    ('34', '34 INTANGIBLES'),
    ('35', '35 ACTIVOS BIOLÓGICOS'),
    ('36', '36 DESVALORIZACIÓN DE ACTIVO INMOVILIZADO'),
    ('37', '37 ACTIVO DIFERIDO'),
    ('38', '38 OTROS ACTIVOS'),
    ('39', '39 DEPRECIACIÓN, AMORTIZACIÓN Y AGOTAMIENTO ACUMULADOS'),
    ('40', '40 TRIBUTOS Y APORTES AL SISTEMA DE PENSIONES Y DE SALUD POR PAGAR'),
    ('41', '41 REMUNERACIONES Y PARTICIPACIONES POR PAGAR'),
    ('42', '42 CUENTAS POR PAGAR COMERCIALES TERCEROS'),
    ('43', '43 CUENTAS POR PAGAR COMERCIALES RELACIONADAS'),
    ('44', '44 CUENTAS POR PAGAR A LOS ACCIONISTAS, DIRECTORES Y GERENTES'),
    ('45', '45 OBLIGACIONES FINANCIERAS'),
    ('46', '46 CUENTAS POR PAGAR DIVERSAS TERCEROS'),
    ('47', '47 CUENTAS POR PAGAR DIVERSAS RELACIONADAS'),
    ('48', '48 PROVISIONES'),
    ('49', '49 PASIVO DIFERIDO'),
    ('50', '50 CAPITAL'),
    ('51', '51 ACCIONES DE INVERSIÓN'),
    ('52', '52 CAPITAL ADICIONAL'),
    ('56', '56 RESULTADOS NO REALIZADOS'),
    ('57', '57 EXCEDENTE DE REVALUACIÓN'),
    ('58', '58 RESERVAS'),
    ('60', '60 COMPRAS'),
    ('61', '61 VARIACIÓN DE EXISTENCIAS'),
    ('62', '62 GASTOS DE PERSONAL, DIRECTORES Y GERENTES'),
    ('63', '63 GASTOS DE SERVICIOS PRESTADOS POR TERCEROS'),
    ('64', '64 GASTOS POR TRIBUTOS'),
    ('65', '65 OTROS GASTOS DE GESTIÓN'),
    ('66', '66 PÉRDIDA POR MEDICIÓN DE ACTIVOS NO FINANCIEROS AL VALOR RAZONABLE'),
    ('67', '67 GASTOS FINANCIEROS'),
    ('68', '68 VALUACIÓN Y DETERIORO DE ACTIVOS Y PROVISIONES'),
    ('69', '69 COSTO DE VENTAS'),
    ('81', '81 PRODUCCIÓN DEL EJERCICIO'),
    ('82', '82 VALOR AGREGADO'),
    ('83', '83 EXCEDENTE BRUTO (INSUFICIENCIA BRUTA) DE EXPLOTACIÓN'),
    ('84', '84 RESULTADO DE EXPLOTACIÓN'),
    ('85', '85 RESULTADO ANTES DE PARTICIPACIONES E IMPUESTOS'),
    ('87', '87 PARTICIPACIONES DE LOS TRABAJADORES'),
    ('88', '88 IMPUESTO A LA RENTA'),
    ('89', '89 DETERMINACIÓN DEL RESULTADO DEL EJERCICIO'),
    ('91', '91 COSTOS POR DISTRIBUIR.'),
    ('92', '92 COSTOS DE PRODUCCIÓN'),
    ('93', '93 CENTROS DE COSTOS'),
    ('94', '94 GASTOS ADMINISTRATIVOS.'),
    ('95', '95 GASTOS DE VENTAS'),
    ('96', '96 GASTOS FINANCIEROS'),
    ('70', '70 VENTAS'),
    ('71', '71 VARIACIÓN DE LA PRODUCCIÓN ALMACENADA'),
    ('72', '72 PRODUCCIÓN DE ACTIVO INMOVILIZADO'),
    ('73', '73 DESCUENTOS, REBAJAS Y BONIFICACIONES OBTENIDOS'),
    ('74', '74 DESCUENTOS, REBAJAS Y BONIFICACIONES CONCEDIDOS'),
    ('75', '75 OTROS INGRESOS DE GESTIÓN'),
    ('76', '76 GANANCIA POR MEDICIÓN DE ACTIVOS NO FINANCIEROS AL VALOR RAZONABLE'),
    ('77', '77 INGRESOS FINANCIEROS'),
    ('78', '78 CARGAS CUBIERTAS POR PROVISIONES'),
    ('79', '79 CARGAS IMPUTABLES A CUENTAS DE COSTOS Y GASTOS')
]

tipo_cuenta=[
    ('AC', 'Activo Circulante'), 
    ('ANC', 'Activo No Circulante'), 
    ('P', 'Pasivo'), 
    ('PT', 'Patrimonio'), 
    ('C', 'Costoso gastos'),
    ('I', 'Ingresos'),
    ('CC', 'Cuentas de Cierre'),
    ('CEA', 'Cuentas Analíticas de Explotación')
]

valores_tipo_monto = [
    ('D', 'Debe'),
    ('H', 'Haber')
]